from odoo import models, _
from odoo.exceptions import UserError


class VarShipmentXlsx(models.AbstractModel):
    _name = 'report.ssi_custom.var_shipment_report_xls'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, lines):
        sheet = workbook.add_worksheet('Product Packaging')
        format1 = workbook.add_format({'font_size': 12, 'align': 'left', 'bold': True})
        format2 = workbook.add_format({'font_size': 12, 'align': 'left'})
        format3 = workbook.add_format({'num_format': 'mm/dd/yy','font_size': 12, 'align': 'left'})
        current_column = 0
        while current_column < 69:
            if (current_column == 0 or current_column == 1 or current_column == 8):
                sheet.set_column(current_column,current_column,25)
            if(current_column == 4):
                sheet.set_column(current_column,current_column,35)
            else:
                sheet.set_column(current_column,current_column,18)
            current_column += 1
        
        sheet.write(0,0, 'Merchant', format1)
        sheet.write(0,1, 'Customer', format1)
        sheet.write(0,2, 'Warehouse', format1)
        sheet.write(0,3, 'Order Number', format1)
        sheet.write(0,4, 'Product', format1)
        sheet.write(0,5, 'Batch', format1)
        sheet.write(0,6, 'Quantity', format1)
        sheet.write(0,7, 'Ship To Id', format1)
        sheet.write(0,8, 'Ship To Name', format1)
        sheet.write(0,9, 'Ship To Address', format1)     
        sheet.write(0,10, "Ship To Address 2",format1)       
        sheet.write(0,11, 'Ship To City', format1)
        sheet.write(0,12, 'Ship To State', format1)
        sheet.write(0,13, 'Ship To Zip', format1)
        sheet.write(0,14, 'Ship To Country', format1)
        sheet.write(0,15, 'Date Of Order', format1)
        sheet.write(0,16, 'Ship To Email', format1)
        sheet.write(0,17, 'Ship Today Phone', format1)
        sheet.write(0,18, 'Ship Tonight Phone', format1)
        sheet.write(0,19, 'Carrier Service', format1)
        sheet.write(0,20, 'Carrier Instruction', format1)
        sheet.write(0,21, 'PO number', format1)
        sheet.write(0,22, 'Pay Type', format1)
        sheet.write(0,23, 'Date To Ship', format1)
        sheet.write(0,24, 'Date To Arrive', format1)
        sheet.write(0,25, 'Master Ref No', format1)
        sheet.write(0,26, 'Stop No', format1)     
        sheet.write(0,27, "No Of Stops",format1)       
        sheet.write(0,28, 'Cus Pool No', format1)
        sheet.write(0,29, 'Ship Type', format1)
        sheet.write(0,30, 'Product Vendor', format1)
        sheet.write(0,31, 'Broker Id', format1)
        sheet.write(0,32, 'Is Sample', format1)
        sheet.write(0,33, 'User 1', format1)
        sheet.write(0,34, 'Cus Pro No', format1)
        sheet.write(0,35, 'Date To Cancel', format1)     
        sheet.write(0,36, "Carrier Name",format1)       
        sheet.write(0,37, 'Bill To Id', format1)
        sheet.write(0,38, 'Bill To Name', format1)
        sheet.write(0,39, 'Bill To Address', format1)
        sheet.write(0,40, 'Bill To Address2', format1)
        sheet.write(0,41, 'Bill To City', format1)
        sheet.write(0,42, 'Bill To State', format1)
        sheet.write(0,43, 'Bill To Zip', format1)
        sheet.write(0,44, 'Bill To Country', format1)     
        sheet.write(0,45, "Bill To Email",format1) 
        sheet.write(0,46, 'Bill Today Phone', format1)
        sheet.write(0,47, 'Bill Tonight Phone', format1)
        sheet.write(0,48, 'Cus Line No', format1)
        sheet.write(0,49, 'Instruction', format1)
        sheet.write(0,50, 'Vics Bol', format1)
        sheet.write(0,51, 'Vics Master Bol', format1)
        sheet.write(0,52, 'Vics Ref No', format1)
        sheet.write(0,53, 'Vics Ref No', format1)
        counter = 0
        for index, picking in enumerate(lines):
            for line in picking.move_lines:
                counter = counter+1
                sheet.write(counter, 0, "CrownPoint", format2)
                sheet.write(counter, 1, "CrownPoint", format2)
                sheet.write(counter, 2, "ValueAdded", format2)
                sheet.write(counter, 3, line.picking_id.sale_id.name, format2)
                sheet.write(counter, 4, line.product_id.name, format2)
                sheet.write(counter, 5, "", format2)
                sheet.write(counter, 6, line.reserved_availability, format2)
                sheet.write(counter, 7, line.picking_id.partner_id.ref, format2)
                sheet.write(counter, 8, line.picking_id.partner_id.name, format2)
                sheet.write(counter, 9, line.picking_id.partner_id.street, format2)
                sheet.write(counter, 10, line.picking_id.partner_id.street2, format2)   
                sheet.write(counter, 11, line.picking_id.partner_id.city, format2)
                sheet.write(counter, 12, line.picking_id.partner_id.state_id.name, format3)
                sheet.write(counter, 13, line.picking_id.partner_id.zip, format3)
                sheet.write(counter, 14, line.picking_id.partner_id.country_id.name, format2)
                sheet.write(counter, 15, line.picking_id.sale_id.date_order, format3)
                sheet.write(counter, 16, line.picking_id.partner_id.email, format2)
                sheet.write(counter, 17, line.picking_id.partner_id.phone, format2)
                sheet.write(counter, 18, line.picking_id.partner_id.mobile, format2)
                sheet.write(counter, 19, "", format2)
                sheet.write(counter, 20, line.picking_id.note, format2)
                sheet.write(counter, 21, line.picking_id.sale_id.client_order_ref, format2)
                sheet.write(counter, 22, "", format2)
                sheet.write(counter, 23, line.picking_id.scheduled_date, format3)
                sheet.write(counter, 24, line.picking_id.date_deadline, format3)
                sheet.write(counter, 25, "", format2)
                sheet.write(counter, 26, "", format2)
                sheet.write(counter, 27, "", format2)
                sheet.write(counter, 28, "", format2)
                sheet.write(counter, 29, line.picking_id.ship_type, format2)
                sheet.write(counter, 30, "", format2)
                sheet.write(counter, 31, "", format2)
                sheet.write(counter, 32, "", format2)
                sheet.write(counter, 33, "", format2)
                sheet.write(counter, 34, "", format2)
                sheet.write(counter, 35, "", format2)
                sheet.write(counter, 36, "", format2)
                sheet.write(counter, 37, "", format2)
                sheet.write(counter, 38, "", format2)
                sheet.write(counter, 39, "", format2)
                sheet.write(counter, 40, "", format2)
                sheet.write(counter, 41, "", format2)
                sheet.write(counter, 42, "", format2)
                sheet.write(counter, 43, "", format2)
                sheet.write(counter, 44, "", format2)
                sheet.write(counter, 45, "", format2)
                sheet.write(counter, 46, "", format2)
                sheet.write(counter, 47, "", format2)
                sheet.write(counter, 48, "", format2)
                sheet.write(counter, 49, "", format2)
                sheet.write(counter, 50, "", format2)
                sheet.write(counter, 51, "", format2)
                sheet.write(counter, 52, "", format2)
                sheet.write(counter, 53, "", format2)
        
        
