from odoo import models, _
from odoo.exceptions import UserError


class VarShipmentXlsx(models.AbstractModel):
    _name = 'report.ssi_custom.var_shipment_report_xls'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, lines):
        sheet = workbook.add_worksheet('Product Packaging')
        format1 = workbook.add_format({'font_size': 12, 'align': 'left', 'bold': True})
        format2 = workbook.add_format({'font_size': 12, 'align': 'left'})
        format3 = workbook.add_format({'num_format': 'mm/dd/yyyy','font_size': 12, 'align': 'left'})
        current_column = 0
        while current_column < 69:
            if (current_column == 0 or current_column == 1 or current_column == 8):
                sheet.set_column(current_column,current_column,25)
            if(current_column == 4):
                sheet.set_column(current_column,current_column,35)
            else:
                sheet.set_column(current_column,current_column,18)
            current_column += 1
        
        sheet.write(0,0, 'merchant', format1)
        sheet.write(0,1, 'customer', format1)
        sheet.write(0,2, 'warehouse', format1)
        sheet.write(0,3, 'orderno', format1)
        sheet.write(0,4, 'product', format1)
        sheet.write(0,5, 'batch', format1)
        sheet.write(0,6, 'quantity', format1)
        sheet.write(0,7, 'shiptoid', format1)
        sheet.write(0,8, 'shiptoname', format1)
        sheet.write(0,9, 'shiptoaddress', format1)     
        sheet.write(0,10, "shiptoaddress2",format1)       
        sheet.write(0,11, 'shiptocity', format1)
        sheet.write(0,12, 'shiptostate', format1)
        sheet.write(0,13, 'shiptozip', format1)
        sheet.write(0,14, 'shiptocountry', format1)
        sheet.write(0,15, 'dateoforder', format1)
        sheet.write(0,16, 'shiptoemail', format1)
        sheet.write(0,17, 'shiptodayphone', format1)
        sheet.write(0,18, 'shiptonightphone', format1)
        sheet.write(0,19, 'carrierservice', format1)
        sheet.write(0,20, 'carrierinstruction', format1)
        sheet.write(0,21, 'ponumber', format1)
        sheet.write(0,22, 'paytype', format1)
        sheet.write(0,23, 'datetoship', format1)
        sheet.write(0,24, 'datetoarrive', format1)
        sheet.write(0,25, 'masterrefno', format1)
        sheet.write(0,26, 'stopno', format1)     
        sheet.write(0,27, "noofstops",format1)       
        sheet.write(0,28, 'cuspoolno', format1)
        sheet.write(0,29, 'shiptype', format1)
        sheet.write(0,30, 'productvendor', format1)
        sheet.write(0,31, 'brokerid', format1)
        sheet.write(0,32, 'issample', format1)
        sheet.write(0,33, 'user1', format1)
        sheet.write(0,34, 'cusprono', format1)
        sheet.write(0,35, 'datetocancel', format1)     
        sheet.write(0,36, "carriername",format1)       
        sheet.write(0,37, 'billtoid', format1)
        sheet.write(0,38, 'billtoname', format1)
        sheet.write(0,39, 'billtoaddress', format1)
        sheet.write(0,40, 'billtoaddress2', format1)
        sheet.write(0,41, 'billtocity', format1)
        sheet.write(0,42, 'billtostate', format1)
        sheet.write(0,43, 'billtozip', format1)
        sheet.write(0,44, 'billtocountry', format1)     
        sheet.write(0,45, "billtoemail",format1) 
        sheet.write(0,46, 'billtodayphone', format1)
        sheet.write(0,47, 'billtonightphone', format1)
        sheet.write(0,48, 'cuslineno', format1)
        sheet.write(0,49, 'instruction', format1)
        sheet.write(0,50, 'vicsbol', format1)
        sheet.write(0,51, 'vicsmasterbol', format1)
        sheet.write(0,52, 'vicsrefno', format1)
        # sheet.write(0,53, 'Vics Ref No', format1)
        counter = 0
        for index, picking in enumerate(lines):
            for line in picking.move_lines:
                counter = counter+1
                sheet.write(counter, 0, "CrownPoint", format2)
                sheet.write(counter, 1, "CrownPoint", format2)
                sheet.write(counter, 2, "ValueAdded", format2)
                sheet.write(counter, 3, line.picking_id.sale_id.name if line.picking_id.sale_id.name else "", format2)
                sheet.write(counter, 4, line.product_id.default_code if line.product_id.default_code else "", format2)
                sheet.write(counter, 5, "", format2)
                sheet.write(counter, 6, line.reserved_availability if line.reserved_availability else "", format2)
                sheet.write(counter, 7, line.picking_id.partner_id.ref if line.picking_id.partner_id.ref else "", format2)
                sheet.write(counter, 8, line.picking_id.partner_id.name if line.picking_id.partner_id.name else "", format2)
                sheet.write(counter, 9, line.picking_id.partner_id.street if line.picking_id.partner_id.street else "", format2)
                sheet.write(counter, 10, line.picking_id.partner_id.street2 if line.picking_id.partner_id.street2 else "", format2)   
                sheet.write(counter, 11, line.picking_id.partner_id.city if line.picking_id.partner_id.city else "", format2)
                sheet.write(counter, 12, line.picking_id.partner_id.state_id.code if line.picking_id.partner_id.state_id.code else "", format3)
                sheet.write(counter, 13, line.picking_id.partner_id.zip if line.picking_id.partner_id.zip else "", format3)
                sheet.write(counter, 14, line.picking_id.partner_id.country_id.name if line.picking_id.partner_id.country_id.name else "", format2)
                sheet.write(counter, 15, line.picking_id.sale_id.date_order if line.picking_id.sale_id.date_order else "", format3)
                sheet.write(counter, 16, line.picking_id.partner_id.email if line.picking_id.partner_id.email else "", format2)
                sheet.write(counter, 17, line.picking_id.partner_id.phone if line.picking_id.partner_id.phone else "", format2)
                sheet.write(counter, 18, line.picking_id.partner_id.mobile if line.picking_id.partner_id.mobile else "", format2)
                sheet.write(counter, 19, "", format2)
                sheet.write(counter, 20, str(line.picking_id.note).rstrip() if line.picking_id.note else "", format2)
                sheet.write(counter, 21, line.picking_id.sale_id.client_order_ref if line.picking_id.sale_id.client_order_ref else "", format2)
                sheet.write(counter, 22, "", format2)
                sheet.write(counter, 23, line.picking_id.scheduled_date if line.picking_id.scheduled_date else None, format3)
                sheet.write(counter, 24, line.picking_id.date_deadline if line.picking_id.date_deadline else "", format3)
                sheet.write(counter, 25, "", format2)
                sheet.write(counter, 26, "", format2)
                sheet.write(counter, 27, "", format2)
                sheet.write(counter, 28, "", format2)
                sheet.write(counter, 29, line.picking_id.ship_type if line.picking_id.ship_type else "", format2)
                sheet.write(counter, 30, "", format2)
                sheet.write(counter, 31, "", format2)
                sheet.write(counter, 32, "", format2)
                sheet.write(counter, 33, "", format2)
                sheet.write(counter, 34, "", format2)
                sheet.write(counter, 35, "", format3)
                sheet.write(counter, 36, "", format2)
                sheet.write(counter, 37, "", format2)
                sheet.write(counter, 38, "", format2)
                sheet.write(counter, 39, "", format2)
                sheet.write(counter, 40, "", format2)
                sheet.write(counter, 41, "", format2)
                sheet.write(counter, 42, "", format2)
                sheet.write(counter, 43, "", format2)
                sheet.write(counter, 44, "", format2)
                sheet.write(counter, 45, "", format2)
                sheet.write(counter, 46, "", format2)
                sheet.write(counter, 47, "", format2)
                sheet.write(counter, 48, "", format2)
                sheet.write(counter, 49, "", format2)
                sheet.write(counter, 50, "", format2)
                sheet.write(counter, 51, "", format2)
                sheet.write(counter, 52, "", format2)
                # sheet.write(counter, 53, "", format2)
        
        
